---
- name: Update systems, verify Docker, and report disk usage on EC2 instances
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Update and upgrade packages on Ubuntu systems
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_os_family == "Debian"

    - name: Update packages on Amazon Linux systems
      yum:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Verify Docker version
      command: docker --version
      register: docker_version
      changed_when: false

    - name: Display Docker version
      debug:
        msg: "Docker version: {{ docker_version.stdout }}"

    - name: Report disk usage
      command: df -h
      register: disk_usage
      changed_when: false

    - name: Display disk usage
      debug:
        msg: "{{ disk_usage.stdout }}"
